.TH "ApacheTerminal Commands" 1 "April 17 2024"

.SH "All Commands documentation commands:"
.IP \(bu 2
* atm cd
.IP \(bu 2
* atm con
.IP \(bu 2
* atm lf
.IP \(bu 2
* atm make
.IP \(bu 2
* atm rm
.IP \(bu 2
* atm say

.SH "Misc Commands:"
.IP \(bu 2
* shutdown - exits the program
.IP \(bu 2
* clear - clears the terminal screen

.SH "Games & other programs:"
.IP \(bu 2
* random passwd - genrates a random 12 diget passowrd
.IP \(bu 2
* calculator - simple calculator app
.IP \(bu 2
* debugger - rubber duck code debugger (type 'quit' to quit the debugger program)

