.TH ApacheTerminal 1 "April 14 2024" "ApacheTerminal Version <2.1.8>" "ApacheTerminal Command Manual" 
.SH NAME
cd \- change directory
.SH SYNOPSIS
.B cd 
[\fIDirectoryName\fR]
.SH DESCRIPTION
changes the current working directory to the directory specified by the user.
.sp 0 
Users can specify the path to the desired directory as an argument.
.SH OPTIONS
.TP
.B atm cd
Display help information.
.B -cd
Goes back a directory.
.SH USAGE EXAMPLE:
---------------------------------
.sp 0
User@Example:~$ cd Directory
.sp 0
User@Example:~/Directory$
.sp 0
[ ^ Change the current directory to 'Directory' ]
.sp 0
---------------------------------
.SH IMPLEMENTATION
ApacheTerminal Version <2.1.8> 2024
.sp 0
Copyright (C) 2024 Apache Software Labs.
.sp 0
LICENSE: GNU GPL Version 3 or later. For more license info: <https://www.gnu.org/licenses/gpl-3.0.en.html>
.SH REPORTING BUGS
Send a comprehensive email or issue on GitHub repository.
.sp 0
Email: longnecklion126@gmail.com
.sp 0
GitHub: https://github.com/longnecklion000
.SH AUTHORS
PoopDogg - (GitHub: https://github.com/longnecklion000) - (Email: longnecklion126@gmail.com)

