.TH ApacheTerminal 1 "April 14 2024" "ApacheTerminal Version <2.1.8>" "ApacheTerminal Command Manual" 
.SH NAME
rm \- remove
.SH SYNOPSIS
.B rm
[\fIFileName\fR]... [\fIDirectoryName\fR]
.SH DESCRIPTION
Removes a specified file or directory that the user chooses.
.SH OPTIONS
.TP
.B atm rm
Display help information.
.SH USAGE EXAMPLE:
-----------------------------------------
.sp 0
User@Example:~$ rm File.txt
.sp 0
[ ^ removed the specified file, 'File.txt' ]

User@Example:~$ rm Directory
.sp 0
[ ^ removed the specified directory, 'Directory' ]
.sp 0
-----------------------------------------
.SH IMPLEMENTATION
ApacheTerminal Version <2.1.8> 2024
.sp 0
Copyright (C) 2024 Apache Software Labs.
.sp 0
LICENSE: GNU GPL Version 3 or later. For more license info: <https://www.gnu.org/licenses/gpl-3.0.en.html>
.SH REPORTING BUGS
Send a comprehensive email or issue on GitHub repository.
.sp 0
Email: longnecklion126@gmail.com
.sp 0
GitHub: https://github.com/longnecklion000
.SH AUTHORS
PoopDogg - (GitHub: https://github.com/longnecklion000) - (Email: longnecklion126@gmail.com)
