.TH ApacheTerminal 1 "April 14 2024" "ApacheTerminal Version <2.1.8>" "ApacheTerminal Command Manual" 
.SH NAME
say \- say what i say
.SH SYNOPSIS
.B say
[\fI'Somthing'\fR]
.SH DESCRIPTION
The user can type 'say' followed by something they want to get printed back to them. 
.sp 0
This functions like the 'echo' command in Linux. The command doesn't need quotes to print something back to the user,
.sp 0
and it can print sentences including spaces.
.SH OPTIONS
.TP
.B atm say 
Display help information.
.SH USAGE EXAMPLE:
-----------------------------------------
.sp 0
User@Example:~$ say Hello World!
.sp 0
Hello World!
.sp 0
User@Example:~$
.sp 0
[ ^ printed back what the user wanted to say, 'Hello World!' ]
.sp 0
-----------------------------------------
.SH IMPLEMENTATION
ApacheTerminal Version <2.1.8> 2024
.sp 0
Copyright (C) 2024 Apache Software Labs.
.sp 0
LICENSE: GNU GPL Version 3 or later. For more license info: <https://www.gnu.org/licenses/gpl-3.0.en.html>
.SH REPORTING BUGS
Send a comprehensive email or issue on GitHub repository.
.sp 0
Email: longnecklion126@gmail.com
.sp 0
GitHub: https://github.com/longnecklion000
.SH AUTHORS
longnecklion000 - (GitHub: https://github.com/longnecklion000) - (Email: longnecklion126@gmail.com)
